security:
    providers:
        in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(?:_(?:profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: in_memory
            logout:
                path: app_logout
                # target: / # opcjonalnie

    access_control: []
