services:

  php-fpm:
    build:
      dockerfile: docker/php/Dockerfile
    container_name: receipts-php-fpm
    volumes:
      - .:/app
    networks:
      - receipts-net

  nginx:
    image: nginx:latest
    container_name: receipts-nginx
    ports:
      - "8082:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - receipts-net

  db:
    image: postgres:16-alpine
    container_name: receipts-db
    environment:
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=symfony
      - POSTGRES_DB=app
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - receipts-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./docker/pgadmin4/data:/var/lib/postgresql/data
    depends_on:
      - db
    networks:
      - receipts-net

networks:

  receipts-net:
    driver: bridge
